# Files and directories #######################################################

music_directory		"nfs://steve/data/media/music/library"
playlist_directory	"~/.config/mpd/playlists"
state_file		"~/.local/state/mpd/state"

database {
	plugin	"proxy"
	host	"steve"
	port	"6600"
}

# General music daemon options ################################################

port			"6600"
restore_paused		"yes"

# Audio Output ################################################################

audio_output {
	type		"pipewire"
	name		"PipeWire Sound Server"
	mixer_type	"none"
}

# Normalization automatic volume adjustments ##################################

replaygain		"album"
