# Files and directories #######################################################

music_directory		"~/music"
playlist_directory	"~/.config/mpd/playlists"
db_file			"~/.config/mpd/database"
state_file		"~/.local/state/mpd/state"

# General music daemon options ################################################

port			"6600"
restore_paused		"yes"

# Audio Output ################################################################

audio_output {
	type		"pipewire"
	name		"PipeWire Sound Server"
	mixer_type	"none"
}

# Normalization automatic volume adjustments ##################################

replaygain		"album"
