directory: ~/music
library: ~/music/library.db
per_disc_numbering: yes

import:
    copy: yes

paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
    singleton: $artist/$album%aunique{}/$disc-$track $title
    comp: Compilations/$album%aunique{}/$disc-$track $title

plugins: fetchart mpdupdate scrub replaygain info mbsync mpd_tracker
replaygain:
    backend: ffmpeg
    overwrite: yes

