directory: ~/music
library: ~/music/library.db
per_disc_numbering: yes

import:
    copy: yes

paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
    singleton: $artist/$album%aunique{}/$disc-$track $title
    comp: $albumartist/$album%aunique{}/$disc-$track $title

plugins: fetchart mpdupdate scrub replaygain info mbsync smartplaylist mpd_tracker mpd_dj
fetchart:
  sources:
    - filesystem
    - coverart
    - itunes
replaygain:
    backend: ffmpeg
smartplaylist:
    relative_to: ~/music
    playlist_dir: ~/.config/mpd/playlists
    playlists:
      - name: "The Backlog.m3u"
        query: ^play_count:1..

      - name: "New Additions.m3u"
        query: "play_count:1.. added:-6m.. added-"
